<h2 style = "color : Brown"> Case Study - Cricket Tournament </h2>

<h4 style = "color : Sky blue"> Example - 1</h4>  

##### Players list contain the height(inches) and weight(lbs) data for all the players

In [85]:
# list of height and weight of the players.
players = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209), (71, 200), (76, 231), (71, 180), (73, 188), (73, 180)]

In [87]:
len(players)

12

In [89]:
players[1][1]

215

In [91]:
import numpy as np

np_players = np.array(players)

In [93]:
np_players

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       ...,
       [ 71, 180],
       [ 73, 188],
       [ 73, 180]])

In [95]:
type(np_players)

numpy.ndarray

MANY ROWS AND 2 COLUMNS (2 COLUNS IS CALLED 2 ARRAY)

<h4 style = "color : Sky blue"> Example - 2 (Numpy Attributes)</h4>

##### Print the structure of the 2-D Array

In [99]:
# As you learnt in this video, NumPy arrays have certain features that help in analysing multidimensional arrays. Some features are as follows:

# shape: It represents the shape of an array as the number of elements in each dimension.
# ndim: It represents the number of dimensions of an array. For a 2D array, ndim = 2.

In [101]:
np_players.shape

(12, 2)

##### Print the dimensions of the array

In [104]:
np_players.ndim

2

##### Print the data type of elements in the array

In [107]:
np_players.dtype

dtype('int32')

Data Type	   Description	            itemsize
int32	       32-bit integer	        4 bytes
int64	       64-bit integer	        8 bytes
float32	       32-bit float  	        4 bytes
float64	       64-bit float	            8 bytes
bool	       Boolean (True/False) 	1 byte

##### Print the size of a single item of the array

In [111]:
np_players.itemsize

4

In [113]:
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.itemsize)

4


<h4 style = "color : Sky blue"> Example - 3</h4>

##### Convert the heights to meters and weights to kg 

In [116]:
# MULTIPLY WEIGHTS WITH 0.0254 AND HEIGHTS WITH 0.453592 
players_converted = np_players * [0.0254, 0.453592]

In [118]:
players_converted

array([[ 1.8796  , 81.64656 ],
       [ 1.8796  , 97.52228 ],
       [ 1.8288  , 95.25432 ],
       ...,
       [ 1.8034  , 81.64656 ],
       [ 1.8542  , 85.275296],
       [ 1.8542  , 81.64656 ]])

<h4 style = "color : Sky blue"> Sub-Setting 2-D Arrays</h4>

##### Fetch the first row from the array 

In NumPy, the dimension is called axis. In NumPy terminology, for 2-D arrays:

axis = 0 - refers to the rows
axis = 1 - refers to the columns

In [122]:
players_converted[0]

array([ 1.8796 , 81.64656])

##### Fetch the first row 2nd element from the array 

In [125]:
players_converted[0][1]

81.64656

##### Fetch the first column from the array 

In [128]:
# SYNTAX NA[ROW][COL]  ROW =: COZ NEED ALL ROW DATA  COL=0 COZ FIRST COLUMN
players_converted[:, 0]

array([1.8796, 1.8796, 1.8288, ..., 1.8034, 1.8542, 1.8542])

##### Fetch the height (1st column) of 9th player from the array 

In [179]:

players_converted[8][0]

1.9304

In [ ]:
players_converted[124,0]

<h4 style = "color : Sky blue"> Conditional Sub-Setting Arrays</h4>

##### Fetch height and weight of players with height above 1.8m


In [ ]:
tall_players = players_converted[players_converted[:,0] > 1.8]

In [ ]:
tall_players

In [ ]:
k = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188)]
k1=np.array(k)
k1

In [ ]:
# In NumPy, when you're working with a 2D array, the syntax array[:, 0] means:
# : → all rows
# 0 → column index 0
tall_players1 = k1[k1[:,0] > 73]
tall_players1

In [136]:
players_converted.shape

(12, 2)

In [138]:
tall_players.shape

(936, 2)

##### Skills Array - holds the player key skills.

In [181]:
skills = np.array(['Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman','Bowler'])
print(skills)
skills.size

['Keeper' 'Batsman' 'Bowler' ... 'Bowler' 'Batsman' 'Bowler']


12

In [183]:
# since players converted and skills have same rows you can check the batsama ppl

##### Fetch Heights of the Batsmen

In [186]:
batsmen = players_converted[skills == 'Batsman']
# IMPORTANT
# since players converted and skills have same rows you can check the batsama ppl
# skills == 'Batsman'gives output as true or false so thats why you get the data of weights after you use another array

In [188]:
batsmen.shape

(6, 2)

In [190]:
# Set NumPy print options
np.set_printoptions(edgeitems=3, threshold=10, suppress=True)

# Now print the first column
print(batsmen[:, 0])

[1.8796 1.8542 1.7526 1.8034 1.9304 1.8542]


In [192]:
# batsmen[:, 0] this shows all 323 

# Which of the following would extract all the rows of the first 3 columns in a 2D array?
array_name[ : , :3] 

✅ What is a 2D list?
A 2D list is like a table – a list of lists.

Example:
THIS HAS 2 ROWS 3 COLUMNS
two_d = [
  [1, 2, 3],
  [4, 5, 6]
]

A multidimensional list means a list that can go beyond 2 levels — it could be 3D, 4D, etc.

Example of a 3D list:

three_d = [
  [
    [1, 2], 
    [3, 4]
  ],
  [
    [5, 6], 
    [7, 8]
  ]
]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] IS THIS 2D OR 3D

💡 THIS is  2D Because:

It has rows and columns

Each row is a list of numbers

There are 3 rows and 4 columns

So it's a 2D structure (like a table 📊).

🧠 If it were 3D:
It would look like a collection of 2D arrays, stacked together.

Example of 3D:

python
Copy
Edit
[
 [[11, 12], [13, 14]],
 [[21, 22], [23, 24]]
]
This has 2 blocks, each block is 2x2.

In [177]:
import numpy as np

# Define the 2D array
arr = np.array([[11, 12, 13, 14],
                [21, 22, 23, 24],
                [31, 32, 33, 34]])

# 1. First column
print(arr[:, 0])

# 2. First row
print(arr[0])

# 3. Last column
print(arr[:, -1])

# 4. Last row
print(arr[-1])


[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [83]:
# border array=1 middle all 0
import numpy as np

# Take input
n = int(input())

# Create an n x n array of ones
arr = np.ones((n, n), dtype=int)

# Fill the inner part with 0s (if n > 2)
if n > 2:
    arr[1:-1, 1:-1] = 0

# Print the result
print(arr)


 3


[[1 1 1]
 [1 0 1]
 [1 1 1]]


📌 arr[1:-1, 1:-1] means:
1:-1 on rows → selects from row index 1 up to second last row.

1:-1 on columns → selects from column index 1 up to second last column.

So, it selects just the inner part (excluding the outermost border):

[1 1]
[1 1]

Now when you do:
arr[1:-1, 1:-1] = 0
You’re saying:

🔄 "Replace the inner block with 0s."