The learning objectives of this section are:

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 


In [2]:
import numpy as np

<h4 style = "color : Sky blue"> Example - 1 (Arithmatric Operations)</h4>  


In [5]:
array1 = np.array([10,20,30,40,50])
array2 = np.arange(5)

In [7]:
array1

array([10, 20, 30, 40, 50])

In [9]:
array2

array([0, 1, 2, 3, 4])

In [11]:
# Add array1 and array2.
array3 = array1 + array2

In [13]:
array3

array([10, 21, 32, 43, 54])

<h4 style = "color : Sky blue"> Example - 2</h4>  

In [16]:
array4 = np.array([1,2,3,4])

In [18]:
array4 + array1

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [20]:
print (array1.shape)

(5,)


In [22]:
print (array4.shape)

(4,)


<h4 style = "color : Sky blue"> Example - 3</h4>  

In [31]:
array = np.linspace(1, 10, 5)
array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
array*2

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [35]:
array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
array**2

array([  1.    ,  10.5625,  30.25  ,  60.0625, 100.    ])

<h4 style = "color : Sky blue"> Stacking Arrays</h4> 

hstack: It puts two arrays with the same number of rows together. By using this command, the number of rows stays the same, while the number of columns increases. 
vstack: It puts two arrays on top of each other. This command works only when the number of columns in both the arrays is the same. This command can only change the number rows of an array. 
reshape: It can change the shape of an array as long as the number of elements in the array before and after the reshape operation is the same. 

In [39]:
# Note that np.hstack(a, b) throws an error - you need to pass the arrays as a list
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [41]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [43]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
k=np.arange(12).reshape(4,3)
k

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
k=k.reshape(4,4)
k

ValueError: cannot reshape array of size 12 into shape (4,4)

In [59]:
k=k.reshape(3,4)
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
array1 = np.arange(12).reshape(3,4) #3x4
array2 = np.arange(20).reshape(5,4) #5x4

In [49]:
print (array1, '\n', array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [51]:
np.vstack((array1,array2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

<h4 style = "color : Sky blue"> Example - 4 (Numpy Built-in functions)</h4>  

In [35]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np.power(array1, 3)

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [38]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
x = np.array([-2,-1, 0, 1,2])
x

array([-2, -1,  0,  1,  2])

In [40]:
abs(x)

array([2, 1, 0, 1, 2])

In [41]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [63]:
# quiz
p=[[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p, -1)
# Step-by-step explanation:
# First, convert p to a NumPy array.

# The total number of elements in p is 3 × 2 = 6.

# np.reshape(p, -1) tells NumPy:
# “Reshape this into 1 dimension, and automatically figure out the correct length (which is 6).”

array([1, 5, 3, 7, 4, 9])

In [ ]:
Consider an (11,12) shape array. What is the index (x,y) of the 100th element? Note: For counting the elements, go row-wise. For example, in the array:

[[1, 5, 9],

 [3, 0, 2]]

the 5th element would be '0'.

In [67]:
Consider the array provided below: 



[[1, 2, 3, 4, 5]

 [6, 7, 8, 9, 10]

 [11, 12, 13, 14, 15]

 [16, 17, 18, 19, 20]]

Now, you are expected to generate the following array out of it:



[[1, 3]

 [5, 7]

 [9, 11]

 [13, 15]

 [17, 19]]

Which code will give you the correct output?

print(array_1.reshape(5, 4)[array_1%2 != 0]) 

 

print(array_1[array_1%2 != 0]) 

 

print(array_1[array_1%2 == 0].reshape(5, 2)) 

 

print(array_1[array_1%2 != 0].reshape(5, 2))  correct ans



In [ ]:
Suppose you have an array 'p'

[[1, 5],
 [3, 7],
 [4, 9]]
What will be the output of the following code?

np.reshape(p, (1, -1))

<h4 style = "color : Sky blue"> Example - 5 (Trignometric functions)</h4>  

In [42]:
np.pi

3.141592653589793

In [43]:
theta = np.linspace(0, np.pi, 5)

In [44]:
theta

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [45]:
np.sin(theta)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [46]:
np.cos(theta)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

In [47]:
np.tan(theta)

array([ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16, -1.00000000e+00,
       -1.22464680e-16])

<h4 style = "color : Sky blue"> Example - 6 (Exponential and logarithmic functions)</h4>  

In [79]:
x = [1, 2, 3, 10]
x = np.array(x)

In [81]:
np.exp(x) # e=2.718...

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 2.20264658e+04])

In [83]:
# 2^1, 2^2, 2^3, 2^10
np.exp2(x)

array([   2.,    4.,    8., 1024.])

In [85]:
np.power(x,3)

array([   1,    8,   27, 1000], dtype=int32)

In [87]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 2.30258509])

In [89]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 3.32192809])

In [91]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 1.        ])

In [93]:
np.log

<ufunc 'log'>

<h4 style = "color : Sky blue"> Example - 7</h4>  

In [95]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [97]:
y = x * 10
y

array([ 0, 10, 20, 30, 40])

In [99]:
y = np.empty(5)
y

array([  1.    ,  10.5625,  30.25  ,  60.0625, 100.    ])

In [101]:
np.multiply(x, 12, out=y)

array([ 0., 12., 24., 36., 48.])

In [103]:
y

array([ 0., 12., 24., 36., 48.])

In [105]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
np.power(2, x, out=y)

ValueError: operands could not be broadcast together with shapes () (5,) (10,) 

In [107]:
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [109]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

<h4 style = "color : Sky blue"> Example - 8 (Aggregates)</h4>  

In [67]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [69]:
sum(x)

15

In [68]:
np.add.reduce(x)

15

In [70]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [72]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

#### Apply Basic Linear Algebra Operations

NumPy provides the ```np.linalg``` package to apply common linear algebra operations, such as:
* ```np.linalg.inv```: Inverse of a matrix
* ```np.linalg.det```: Determinant of a matrix
* ```np.linalg.eig```: Eigenvalues and eigenvectors of a matrix
    
Also, you can multiple matrices using ```np.dot(a, b)```. 


In [1]:
# np.linalg documentation
# help(np.linalg) too  many pages 

In [74]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [75]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

##### Rank of a matrix

In [76]:
np.linalg.matrix_rank(A)

3

##### Trace of matrix A

In [77]:
np.trace(A)

11

##### Determinant of a matrix

In [78]:
np.linalg.det(A)

-306.0

##### Inverse of matrix A

In [87]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [79]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [84]:
B = np.linalg.inv(A)

In [85]:
np.matmul(A,B) #actual matrix multiplication

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [-4.16333634e-17,  1.38777878e-16,  1.00000000e+00]])

In [86]:
A * B

array([[ 1.05882353, -0.00326797, -0.02287582],
       [ 0.23529412,  0.26143791,  0.4248366 ],
       [-0.23529412,  1.20261438,  0.36601307]])

##### Matrix A raised to power 3

In [88]:
np.linalg.matrix_power(A,3) # matrix multiplication A A A

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])