# Numpy vs Lists 

NumPy, which stands for ‘Numerical Python’, is a library meant for scientific calculations. The basic data structure of NumPy is an array.
A NumPy array is a collection of values stored together, similar to a list. 

list la if i want to multiply each element with 2 should write looping statement .In Numpy its not needed
Array is full integers or full strings

Creating NumPy Arrays
There are two ways to create NumPy arrays, which are mentioned below.

By converting the existing lists or tuples to arrays using np.array
By initialising fixed-length arrays using the NumPy functions

The only difference between a NumPy array and a list is that the elements in the NumPy array are separated by a space instead of a comma.
Hence, this is an aesthetic feature that differentiates a list and a NumPy array.

In [1]:
#Let's define a list in python.
heights = [74, 75, 72, 72, 71]

In [3]:
# Print the heights.
heights

[74, 75, 72, 72, 71]

In [4]:
# Try to multiple heights with a scalar.
heights * 2.54

TypeError: can't multiply sequence by non-int of type 'float'

In [9]:
import numpy as np

In [11]:
# Deine a NumPy array
np_heights = np.array([74, 75, 72, 72, 71])

In [13]:
np_heights

array([74, 75, 72, 72, 71])

In [15]:
# Print the type of a NumPy array.
type(np_heights)

numpy.ndarray

In [17]:
# Multiple height (NumPy array) with a scalar.
np_heights * 2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])


#### NumPy comes with its own set of methods and operations

In [21]:
# Let's define two lists and perform '+' operation on that.
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [23]:
# Let's define two NumPy array and perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np1 + np2

array([5, 7, 9])

#### Working with N-D Arrays

In [26]:
np_heights

array([74, 75, 72, 72, 71])

In [28]:
type(np_heights)

numpy.ndarray

In [34]:
# Question
# Ceate a 1-d array using the following elements (1.0, 2, 3.5, 0.2, True).
# (Note that ‘True’ must be provided as a Boolean value, not as a string.)
a=np.array( [1.0, 2, 3.5, 0.2, True] ) 

In [36]:
type(a)

numpy.ndarray

In [ ]:
# True (capital T) is a boolean in Python.

# NumPy will automatically upcast the boolean to match the dominant data type, which is float here.

# So, True becomes 1.0 in the array.