### Compare Computation Times in NumPy and Standard Python Lists

Now that we know how to use numpy, let us see code and witness the key advantages of numpy i.e. convenience and speed of computation. 

In the data science landscape, you'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.   

Let's compare the computation times of arrays and lists for a simple task of calculating the element-wise product of numbers. 

In [10]:
import time

In [15]:
## Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0
print (t1-t0)

# numpy array 
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
product_numpy = array_1 * array_2
t1 = time.time()
numpy_time = t1 - t0
print (t1-t0)

print("The ratio of time taken is {}".format(list_time//numpy_time))

0.1251368522644043
0.005321025848388672
The ratio of time taken is 23.0


In this case, numpy is **an order of magnitude faster** than lists. This is with arrays of size in millions, but you may work on much larger arrays of sizes in order of billions. Then, the difference is even larger.

Some reasons for such difference in speed are:
* NumPy is written in C, which is basically being executed behind the scenes
* NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists


The following discussions demonstrate the differences in speeds of NumPy and standard python:
1. https://stackoverflow.com/questions/8385602/why-are-numpy-arrays-so-fast
2. https://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists

Given a 2D NumPy array, sort it by the 1st column. Print the final sorted array as a NumPy array only.
Note: If two values in the 1st column are equal then the column in which the 2nd column value is lesser should come first. If the value in the second column is also the same then go to the third value and so on.

Example:

Input 1:

[[9 3 2]

 [4 0 1]

 [5 8 6]]

Output 1:

[[4 0 1]

 [5 8 6]

 [9 3 2]]

Input 2:

[[9 3 2]

 [4 0 1]

 [9 8 6]]

Output 2:

[[4 0 1]

 [9 3 2]

 [9 8 6]]



Explanation:

Example 1: Notice that the values in the first column are sorted. Also notice that the whole row should be moved and not just the individual values in the first column. For example, the row with the smallest value, i.e. 4 was moved as a whole. 

Example 2: Since this time the first row contains two 9s, the row in which the value in the second column is lesser came first.

In [3]:
# Reading the input list METHOD 1
import ast,sys
# input_str = sys.stdin.read()
input_str=input()
input_list = ast.literal_eval(input_str)

# Import the NumPy package
import numpy as np

# Converting the list to a NumPy array
n_array = np.array(input_list)

# Sort the array using the argsort() argument. You can also specify the type of
# sort you need in the argsort() argument but it isn't necessary. Notice the 
# indexing is the main key here. The array is sorted by the row or column that you
# specify in the index
for i in range(len(n_array[0, :])):
    n_array = n_array[n_array[:,-1-i].argsort()]

# Print the final sorted array
print(n_array)

 [     [9, 3, 2],     [4, 0, 1],     [9, 8, 6]]


[[4 0 1]
 [9 3 2]
 [9 8 6]]


In [5]:
# METHOD 2
import numpy as np

# Example input
arr = np.array([
    [9, 3, 2],
    [4, 0, 1],
    [9, 8, 6]
])

# Use np.lexsort to sort by all columns starting from the last
sorted_arr = arr[np.lexsort(arr.T[::-1])]
print(sorted_arr)


[[4 0 1]
 [9 3 2]
 [9 8 6]]
