<h2 style = "color : Brown"> Creating NumPy Arrays </h2 >



# ARRAY CREATION
The following ways are commonly used when you know the size of the array beforehand:
np.ones(): It is used to create an array of 1s.
np.zeros(): It is used to create an array of 0s.
np.random.randint(): It is used to create a random array of integers within a particular range.
np.random.random(): It is used to create an array of random numbers.
np.arange(): It is used to create an array with increments of fixed step size.
np.linspace(): It is used to create an array of fixed length.

 The following ways are commonly used when you know the size of the array beforehand:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [3]:
import numpy as np

##### Tip: Use help to see the syntax when required

In [5]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.

##### Creating a 1 D array of ones

In [7]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [9]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [14]:
arr = np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [16]:
arr.dtype

dtype('int32')

##### Creating a 5  x 3 array of ones


In [19]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### Creating array of zeros

In [22]:
np.zeros(5)
# BY DEFAULT FLOAT IT AGAIN DEPENDS ON ENVIRONMENT 

array([0., 0., 0., 0., 0.])

In [24]:
# convert the type into integer.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [26]:
# Create a list of integers range between 1 to 5.
list(range(1,5))

[1, 2, 3, 4]

In [28]:
np.arange(3)

array([0, 1, 2])

In [30]:
np.arange(3.0)

array([0., 1., 2.])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [33]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

##### Array of random numbers 


In [50]:
# (LOWER BOUND,UPPER BOUND SIZE)  IF YOU PROVIDE ONLY ONE VALUE ITS CONSIDERED AS UPPER BOUND
np.random.randint(2,5, size=10)

array([2, 3, 4, 3, 3, 3, 2, 3, 2, 4])

In [52]:
np.random.randint(2, size=10)

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [38]:
np.random.randint(3,5, size=10)

array([4, 3, 4, 4, 3, 4, 4, 3, 3, 4])

##### 2D Array of random numbers 


In [ ]:
# BY DEFAULT VALUES BETWEEN 0 AND 1

In [41]:
np.random.random([3,4])

array([[0.25464109, 0.01093949, 0.52906496, 0.02871476],
       [0.36603669, 0.46212483, 0.58641987, 0.69747825],
       [0.66274296, 0.79701496, 0.60440997, 0.80770366]])

###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [44]:
# THIS 10 IN INCLUDED IN OUTPUT USUALLY WE GET ONLY TILL 9 KADA THIS IS EXCEPTION
# "Create 20 evenly spaced numbers between 1 and 10 (inclusive)."
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [56]:
import numpy as np

# 1️⃣ np.full()
arr_2d_full = np.full((2, 3), 7)            # 2D: 2 rows, 3 columns filled with 7
arr_3d_full = np.full((2, 2, 3), 5)         # 3D: 2 blocks of 2x3 filled with 5

print("🔹 np.full() 2D:\n", arr_2d_full)
print("🔹 np.full() 3D:\n", arr_3d_full)


🔹 np.full() 2D:
 [[7 7 7]
 [7 7 7]]
🔹 np.full() 3D:
 [[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]


In [58]:

# 2️⃣ np.tile()
arr_2d_tile = np.tile([[1, 2], [3, 4]], (2, 2))       # 2D tile
arr_3d_tile = np.tile(np.array([[[1], [2]]]), (2, 2, 2))  # 3D tile: repeat a simple 3D structure

print("\n🔹 np.tile() 2D:\n", arr_2d_tile)
print("🔹 np.tile() 3D:\n", arr_3d_tile)



🔹 np.tile() 2D:
 [[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]
🔹 np.tile() 3D:
 [[[1 1]
  [2 2]
  [1 1]
  [2 2]]

 [[1 1]
  [2 2]
  [1 1]
  [2 2]]]


🔍 Step-by-step
1️⃣ Original array:
[[1, 2],
 [3, 4]]
2️⃣ Repeat across (columns) → 2 times:
We put each row side-by-side twice:
[[1, 2, 1, 2],
 [3, 4, 3, 4]]
3️⃣ Repeat down (rows) → 2 times:
We repeat the full thing again top to bottom:
[[1, 2, 1, 2],
 [3, 4, 3, 4],
 [1, 2, 1, 2],
 [3, 4, 3, 4]]
✅ Final Output:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]

✅ Step 1: Understand the original array
python
Copy
Edit
np.array([[[1], [2]]])
This is a 3D array. Let’s see what it looks like:

It has 1 "block", and inside that:

Row 1 → [1]

Row 2 → [2]

So visually, think of it as:

[
  [
    [1],
    [2]
  ]
]
Its shape is:

(1, 2, 1) → (depth, rows, columns)
✅ Step 2: What does (2, 2, 2) mean?
It tells NumPy how to repeat the array along each dimension:
2 times in depth (outermost dimension)
2 times in rows (vertical repeat inside each depth block)
2 times in columns (horizontal repeat of numbers)

✅ Step 3: Let’s build the final result
Let’s go one dimension at a time:

Original 3D array:
[
  [
    [1],
    [2]
  ]
]
📦 Step A: Repeat in columns (last number 2)
Inside each row: [1] becomes [1, 1], [2] becomes [2, 2]
[
  [
    [1, 1],
    [2, 2]
  ]
]
📦 Step B: Repeat in rows (middle number 2)
Repeat those rows:
[
  [
    [1, 1],
    [2, 2],
    [1, 1],
    [2, 2]
  ]
]
📦 Step C: Repeat in depth (outermost number 2)
Repeat that whole block again:
[
  [
    [1, 1],
    [2, 2],
    [1, 1],
    [2, 2]
  ],
  [
    [1, 1],
    [2, 2],
    [1, 1],
    [2, 2]
  ]
]


In [60]:

# 3️⃣ np.eye()
arr_2d_eye = np.eye(3)               # Identity matrix (2D only)
# np.eye doesn't work for 3D directly, but we can stack for simulation:
arr_3d_eye = np.array([np.eye(3), np.eye(3)])  # Stack two identity matrices to simulate 3D

print("\n🔹 np.eye() 2D:\n", arr_2d_eye)
print("🔹 np.eye() 3D (simulated by stacking 2D):\n", arr_3d_eye)



🔹 np.eye() 2D:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
🔹 np.eye() 3D (simulated by stacking 2D):
 [[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]


In [62]:

# 4️⃣ np.random.randint()
arr_2d_rand = np.random.randint(0, 10, (2, 3))     # 2D random ints
arr_3d_rand = np.random.randint(10, 100, (2, 2, 3))  # 3D random ints

print("\n🔹 np.random.randint() 2D:\n", arr_2d_rand)
print("🔹 np.random.randint() 3D:\n", arr_3d_rand)



🔹 np.random.randint() 2D:
 [[6 4 9]
 [6 6 4]]
🔹 np.random.randint() 3D:
 [[[13 67 18]
  [49 22 72]]

 [[54 59 68]
  [15 97 40]]]
